file(MAKE_DIRECTORY "${DESTINATION}")
set(found FALSE)
foreach(name LICENSE COPYING)
    if(EXISTS "${SOURCE}/${name}")
        file(COPY "${SOURCE}/${name}" DESTINATION "${DESTINATION}")
        set(found TRUE)
    endif()
endforeach()
if(NAME STREQUAL "drm")
    file(GLOB notices "${SOURCE}/*.c" "${SOURCE}/*.h")
    if(NOT notices)
        message(FATAL_ERROR "Missing libdrm per-file license notices")
    endif()
    file(COPY ${notices} DESTINATION "${DESTINATION}")
elseif(NOT found)
    message(FATAL_ERROR "Missing license for ${NAME}")
endif()