find_program(READELF NAMES llvm-readelf readelf REQUIRED)
execute_process(COMMAND ${CMAKE_COMMAND} -E env LC_ALL=C ${READELF} -h -d "${LIBRARY}"
    OUTPUT_VARIABLE dynamic COMMAND_ERROR_IS_FATAL ANY)
if(NOT dynamic MATCHES "Class:[ \t]+ELF64" OR NOT dynamic MATCHES "Machine:[ \t]+AArch64"
        OR NOT dynamic MATCHES "Type:[ \t]+DYN")
    message(FATAL_ERROR "Runtime must be an ARM64 Android shared library or PIE: ${LIBRARY}")
endif()
if(dynamic MATCHES "\\((RPATH|RUNPATH)\\)")
    message(FATAL_ERROR "Runtime must not embed a loader search path: ${LIBRARY}")
endif()
string(REGEX MATCHALL "Shared library: \\[[^]]+\\]" dependencies "${dynamic}")
if(NOT dependencies)
    message(FATAL_ERROR "Runtime has no inspectable dynamic dependencies: ${LIBRARY}")
endif()
foreach(dependency IN LISTS dependencies)
    if(NOT dependency MATCHES "\\[lib(c|m|dl|android|log)\\.so\\]$")
        message(FATAL_ERROR "Non-system runtime dependency: ${dependency}")
    endif()
endforeach()
message(STATUS "Standalone Android runtime dependency check passed")
