find_program(READELF NAMES llvm-readelf readelf REQUIRED)
execute_process(COMMAND ${CMAKE_COMMAND} -E env LC_ALL=C ${READELF} -d "${LIBRARY}"
    OUTPUT_VARIABLE dynamic COMMAND_ERROR_IS_FATAL ANY)
if(dynamic MATCHES "\\((RPATH|RUNPATH)\\)")
    message(FATAL_ERROR "Runtime must not embed a loader search path: ${LIBRARY}")
endif()
string(REGEX MATCHALL "Shared library: \\[[^]]+\\]" dependencies "${dynamic}")
if(NOT dependencies)
    message(FATAL_ERROR "Runtime has no inspectable dynamic dependencies: ${LIBRARY}")
endif()
foreach(dependency IN LISTS dependencies)
    if(NOT dependency MATCHES "\\[lib(c|m|dl)\\.so\\]$")
        message(FATAL_ERROR "Non-system runtime dependency: ${dependency}")
    endif()
endforeach()
message(STATUS "Standalone Android runtime dependency check passed")