plugins {
    id 'com.android.application'
}

android {
    namespace = 'io.github.mekhontsev.magicdesk.kernel'
    compileSdk = 37

    defaultConfig {
        applicationId = 'io.github.mekhontsev.magicdesk.kernel'
        minSdk = 36
        targetSdk = 36
        versionCode = 110
        versionName = '1.1'
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

apply from: rootProject.file('gradle/release-signing.gradle')
